name: Deploy to GitHub Pages

on:
  push:
    branches: ['*']  # Triggers on push to any branch
  pull_request:
    branches: ['*']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: |
          # Copy all static files to build directory
          mkdir -p ./dist
          cp index.html ./dist/
          cp -r css ./dist/
          cp -r js ./dist/
          
          # Create branch-specific content
          echo "<!-- Branch: ${{ github.ref_name }} -->" >> ./dist/index.html
          
          # Add branch info to JavaScript
          cat >> ./dist/js/main.js << EOF
          
          // Branch information injected during build
          window.GITHUB_BRANCH = '${{ github.ref_name }}';
          window.GITHUB_SHA = '${{ github.sha }}';
          window.BUILD_TIME = '$(date -u +"%Y-%m-%dT%H:%M:%SZ")';
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Deployment job for main/master branch (root domain)
  deploy-main:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (Root)
        id: deployment
        uses: actions/deploy-pages@v4

  # Deployment job for feature branches (subdirectories)
  deploy-branch:
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./artifact

      - name: Extract artifact
        run: |
          cd artifact
          tar -xf artifact.tar
          cd ..

      - name: Setup branch directory
        run: |
          # Create branch-specific directory
          BRANCH_NAME="${{ github.ref_name }}"
          # Sanitize branch name for directory use
          SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
          
          # Create directory for this branch
          mkdir -p "$SAFE_BRANCH_NAME"
          
          # Copy built files to branch directory
          cp -r artifact/* "$SAFE_BRANCH_NAME/"
          
          # Update base href in HTML for subdirectory deployment
          if [ -f "$SAFE_BRANCH_NAME/index.html" ]; then
            sed -i 's|href="css/|href="'"$SAFE_BRANCH_NAME"'/css/|g' "$SAFE_BRANCH_NAME/index.html"
            sed -i 's|src="js/|src="'"$SAFE_BRANCH_NAME"'/js/|g' "$SAFE_BRANCH_NAME/index.html"
          fi
          
          # Create/update branch index
          echo "<!DOCTYPE html><html><head><title>Branch Deployments</title></head><body>" > branches.html
          echo "<h1>Available Branch Deployments</h1><ul>" >> branches.html
          for dir in */; do
            if [ -d "$dir" ] && [ "$dir" != "artifact/" ]; then
              echo "<li><a href=\"${dir%/}/\">$(basename "$dir")</a></li>" >> branches.html
            fi
          done
          echo "</ul></body></html>" >> branches.html

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          BRANCH_NAME="${{ github.ref_name }}"
          SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
          
          git add "$SAFE_BRANCH_NAME/"
          git add branches.html
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy branch: $BRANCH_NAME to subdirectory: $SAFE_BRANCH_NAME"
            git push origin gh-pages
          fi

      - name: Comment deployment URL
        if: github.event_name == 'push'
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
          REPO_NAME="${{ github.repository }}"
          USERNAME=$(echo "$REPO_NAME" | cut -d'/' -f1)
          REPO=$(echo "$REPO_NAME" | cut -d'/' -f2)
          
          DEPLOY_URL="https://${USERNAME}.github.io/${REPO}/${SAFE_BRANCH_NAME}/"
          
          echo "🚀 Branch '$BRANCH_NAME' deployed to: $DEPLOY_URL"
          echo "deployment-url=$DEPLOY_URL" >> $GITHUB_OUTPUT